// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6jqHkcNfnFCtUXSQZFCpjqU2ab9askow',
    appId: '1:510128862602:web:8f575f4067561800ff8473',
    messagingSenderId: '510128862602',
    projectId: 'fashion-store-b10fd',
    authDomain: 'fashion-store-b10fd.firebaseapp.com',
    storageBucket: 'fashion-store-b10fd.firebasestorage.app',
    measurementId: 'G-2WNNZDXG1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRWkWtV6Ghg8HUXEvuFpm_OnPAELYJW_Y',
    appId: '1:510128862602:android:d19a5793976cbb1aff8473',
    messagingSenderId: '510128862602',
    projectId: 'fashion-store-b10fd',
    storageBucket: 'fashion-store-b10fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ8IehabNWqkmpxiNFkJYTOC3jof1Y--g',
    appId: '1:510128862602:ios:f4ceafb6dfb48c44ff8473',
    messagingSenderId: '510128862602',
    projectId: 'fashion-store-b10fd',
    storageBucket: 'fashion-store-b10fd.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ8IehabNWqkmpxiNFkJYTOC3jof1Y--g',
    appId: '1:510128862602:ios:f4ceafb6dfb48c44ff8473',
    messagingSenderId: '510128862602',
    projectId: 'fashion-store-b10fd',
    storageBucket: 'fashion-store-b10fd.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6jqHkcNfnFCtUXSQZFCpjqU2ab9askow',
    appId: '1:510128862602:web:197c8c181807d785ff8473',
    messagingSenderId: '510128862602',
    projectId: 'fashion-store-b10fd',
    authDomain: 'fashion-store-b10fd.firebaseapp.com',
    storageBucket: 'fashion-store-b10fd.firebasestorage.app',
    measurementId: 'G-L854J4VJVN',
  );

}